name: Контроль качества

on:
  push:
  workflow_dispatch:

jobs:
  sonar:
    if: github.repository_owner == 'alei1180'
    uses: autumn-library/workflows/.github/workflows/sonar.yml@v1
    with:
      github_repository: alei1180/curlone
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}